package com.company;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AddCustomer extends JFrame {
    private JPanel panel1;
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;
    private JButton submitButton;
    private JLabel submitSucced;
    private JButton back;


    public AddCustomer() {
        submitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                VideoStore vd = new VideoStore();
                vd.addCustomer(textField1.getText(), Integer.parseInt(textField2.getText()), textField3.getText());
                textField1.setText("");
                textField2.setText("");
                textField3.setText("");
            }
        });
        back.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(10);
        label1.setHorizontalTextPosition(11);
        label1.setText("Name");
        panel1.add(label1);
        textField1 = new JTextField();
        textField1.setDropMode(DropMode.USE_SELECTION);
        textField1.setHorizontalAlignment(0);
        panel1.add(textField1);
        final JLabel label2 = new JLabel();
        label2.setText("Phone Number");
        panel1.add(label2);
        textField2 = new JTextField();
        textField2.setHorizontalAlignment(0);
        panel1.add(textField2);
        final JLabel label3 = new JLabel();
        label3.setText("Address");
        panel1.add(label3);
        textField3 = new JTextField();
        textField3.setHorizontalAlignment(0);
        panel1.add(textField3);
        submitButton = new JButton();
        submitButton.setText("Submit");
        panel1.add(submitButton);
        submitSucced = new JLabel();
        submitSucced.setText("Label");
        panel1.add(submitSucced);
        back = new JButton();
        back.setText("Back");
        panel1.add(back);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
