package com.company;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Window extends JFrame {
    private JPanel panel1;
    private JMenu customers;
    private JMenu rents;
    private JMenu films;
    private JMenuItem addFilm;
    private JMenuItem showFilms;
    private JMenuItem addCustomer;
    private JMenuItem rentByTittle;
    private JMenuItem showCustomers;
    private JMenuItem showDayDevolutions;
    private JMenuItem exit;
    private JMenuItem showLastTenRentsOfCustomers;
    private JMenuItem mostRentedFilm;
    private JMenuItem searchFilmsByCategory;
    private JMenuItem showRents;

    public Window() {
        exit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        addCustomer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                AddCustomer addCustomer = new AddCustomer();
                addCustomer.setVisible(true);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JMenuBar menuBar1 = new JMenuBar();
        menuBar1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(menuBar1);
        customers = new JMenu();
        customers.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        customers.setText("Customers");
        menuBar1.add(customers);
        addCustomer = new JMenuItem();
        addCustomer.setText("Add Customer");
        customers.add(addCustomer);
        showCustomers = new JMenuItem();
        showCustomers.setText("Show Customers");
        customers.add(showCustomers);
        films = new JMenu();
        films.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        films.setText("Films");
        menuBar1.add(films);
        addFilm = new JMenuItem();
        addFilm.setText("Add Film");
        films.add(addFilm);
        showFilms = new JMenuItem();
        showFilms.setText("Show Films");
        films.add(showFilms);
        mostRentedFilm = new JMenuItem();
        mostRentedFilm.setText("Most rented Film");
        films.add(mostRentedFilm);
        searchFilmsByCategory = new JMenuItem();
        searchFilmsByCategory.setText("Search films by Category");
        films.add(searchFilmsByCategory);
        rents = new JMenu();
        rents.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        rents.setText("Rents");
        menuBar1.add(rents);
        rentByTittle = new JMenuItem();
        rentByTittle.setText("Rent by tittle");
        rents.add(rentByTittle);
        showDayDevolutions = new JMenuItem();
        showDayDevolutions.setText("Show day devolutions");
        rents.add(showDayDevolutions);
        showLastTenRentsOfCustomers = new JMenuItem();
        showLastTenRentsOfCustomers.setText("Show the last ten rents of customers");
        rents.add(showLastTenRentsOfCustomers);
        showRents = new JMenuItem();
        showRents.setText("Show Rents");
        rents.add(showRents);
        exit = new JMenuItem();
        exit.setText("Exit");
        menuBar1.add(exit);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
